@startuml
class java.awt.BorderLayout
class java.awt.Color
class java.awt.event.MouseEvent
class java.awt.image.ImageObserver
class java.text.DateFormat
class java.text.DateFormatSymbols
class java.text.SimpleDateFormat
class java.time.LocalDate
class java.util.ArrayList
class java.util.Calendar
class java.util.Date
class java.util.List
class java.util.Random
class javaswingdev.chart.ModelPieChart
class javaswingdev.chart.PieChart
class javax.swing.Icon
class javax.swing.ImageIcon
class javax.swing.JButton
class javax.swing.JComponent
class javax.swing.JFrame
class javax.swing.JPanel
class javax.swing.JScrollPane
class javax.swing.JTextField
class javax.swing.UIManager
class javax.swing.plaf.ColorUIResource
class javax.swing.table.DefaultTableModel
class javax.swing.table.TableModel
class org.jfree.chart.ChartFactory
class org.jfree.chart.ChartPanel
class org.jfree.chart.JFreeChart
class org.jfree.chart.plot.CategoryPlot
class org.jfree.chart.plot.PiePlot
class org.jfree.chart.plot.PlotOrientation
class org.jfree.chart.plot.XYPlot
class org.jfree.chart.renderer.category.BarRenderer
class org.jfree.chart.renderer.category.LineAndShapeRenderer
class org.jfree.data.category.DefaultCategoryDataset
class org.jfree.data.general.DefaultPieDataset
class org.jfree.data.statistics.HistogramDataset
class shorna.moneymanagement.component.ScrollBar
class shorna.moneymanagement.event.EventMenuSelected
class shorna.moneymanagement.model.CategoryTotalModel
class shorna.moneymanagement.model.MonthWiseSummary
class shorna.moneymanagement.model.SummaryModel
class shorna.moneymanagement.model.TransactionModel
class shorna.moneymanagement.repository.TransactionRepository
class shorna.moneymanagement.service.TransactionService
class shorna.moneymanagement.session.Session
class shorna.moneymanagement.utils.PopUpMessage
class shorna.moneymanagement.view.auth.LoginPage
class shorna.moneymanagement.view.constant.TransactionType
class shorna.moneymanagement.view.dashboard.DashboardPage
class shorna.moneymanagement.view.dashboard.form.Analysis
class shorna.moneymanagement.view.dashboard.form.Expense
class shorna.moneymanagement.view.dashboard.form.Home
class shorna.moneymanagement.view.dashboard.form.Income
class shorna.moneymanagement.view.dashboard.form.TransactionHistory
class shorna.moneymanagement.view.dashboard.model.Model_Card
class shorna.moneymanagement.view.dashboard.model.Model_Menu
enum shorna.moneymanagement.view.dashboard.model.StatusType
@enduml