/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shorna.moneymanagement.view.auth;

import shorna.moneymanagement.model.UserModel;
import shorna.moneymanagement.repository.UserRepository;
import shorna.moneymanagement.session.Session;
import shorna.moneymanagement.view.dashboard.DashboardPage;

/**
 *
 * @author Mst. Taslima Aktar Shorna
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftSide = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        image = new javax.swing.JPanel();
        bgImage = new javax.swing.JLabel();
        formSide = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSignup = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(512, 512));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        leftSide.setBackground(new java.awt.Color(255, 255, 255));
        leftSide.setMinimumSize(new java.awt.Dimension(100, 100));
        leftSide.setPreferredSize(new java.awt.Dimension(800, 640));
        leftSide.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(62, 195, 212));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Manage your money");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        leftSide.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        image.setBackground(new java.awt.Color(255, 255, 255));
        image.setLayout(new java.awt.CardLayout());

        bgImage.setBackground(new java.awt.Color(255, 255, 255));
        bgImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shorna/moneymanagement/images/transaction.jpg"))); // NOI18N
        bgImage.setPreferredSize(new java.awt.Dimension(100, 300));
        image.add(bgImage, "card2");

        leftSide.add(image, java.awt.BorderLayout.CENTER);

        getContentPane().add(leftSide);

        formSide.setBackground(new java.awt.Color(191, 219, 238));
        formSide.setPreferredSize(new java.awt.Dimension(400, 640));
        formSide.setLayout(null);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        txtEmail.setCaretColor(new java.awt.Color(204, 204, 204));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEmail.setPreferredSize(new java.awt.Dimension(100, 17));
        formSide.add(txtEmail);
        txtEmail.setBounds(60, 190, 300, 36);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Email");
        formSide.add(jLabel1);
        jLabel1.setBounds(60, 170, 300, 17);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Password");
        formSide.add(jLabel2);
        jLabel2.setBounds(60, 240, 300, 17);

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        formSide.add(btnLogin);
        btnLogin.setBounds(60, 340, 300, 36);

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(10, 96, 106));
        jLabel4.setText("Welcome Back");
        formSide.add(jLabel4);
        jLabel4.setBounds(60, 60, 290, 50);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(62, 195, 212));
        jLabel5.setText("Login Here");
        formSide.add(jLabel5);
        jLabel5.setBounds(60, 100, 280, 43);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("© Mst. Taslima Aktar Shorna");
        formSide.add(jLabel7);
        jLabel7.setBounds(190, 550, 160, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Don't have an account?");
        formSide.add(jLabel8);
        jLabel8.setBounds(140, 420, 150, 36);

        btnSignup.setBackground(new java.awt.Color(191, 219, 238));
        btnSignup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(0, 153, 153));
        btnSignup.setText("Sign Up");
        btnSignup.setBorder(null);
        btnSignup.setBorderPainted(false);
        btnSignup.setContentAreaFilled(false);
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        formSide.add(btnSignup);
        btnSignup.setBounds(290, 420, 70, 36);

        lblMsg.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(204, 0, 0));
        formSide.add(lblMsg);
        lblMsg.setBounds(60, 310, 300, 20);

        txtPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        formSide.add(txtPassword);
        txtPassword.setBounds(60, 260, 300, 36);

        getContentPane().add(formSide);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String email = txtEmail.getText().trim();
        String password = String.valueOf(txtPassword.getPassword());

        try {
            UserRepository userRepository = new UserRepository();
            if (email.matches(".*[a-zA-Z0-9].*") || password.length() > 0) {

                boolean isUserExist = userRepository.isUserAlreadyExist(email);

                if (isUserExist) {
                    UserModel result = userRepository.login(email, password);
                    if (result != null) {
                        try {
                            Session session = new Session(result);
                            new DashboardPage().setVisible(true);
                            this.setVisible(false);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    } else {
                        lblMsg.setText("Email and password didn't match");
                    }
                } else {
                    lblMsg.setText("No user with this email");

                }

            } else {
                lblMsg.setText("Insert username and password!");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    void clearMsg() {
        lblMsg.setText("");
    }
    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        this.dispose();
        new SignupPage().setVisible(true);
    }//GEN-LAST:event_btnSignupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JPanel formSide;
    private javax.swing.JPanel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JPanel leftSide;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
